# Reading the Financial Statement using Python

In [32]:

import yfinance as yf

#import libraries

# Balance Sheet

In [33]:
# Create the functions forget access for balance sheet
def get_balance_sheet_data(symbol):
    # for company symbol
    company = yf.Ticker(symbol)
    # get access of balancesheet
    balance_sheet = company.balance_sheet
    return balance_sheet

symbol = "TCS"
# balance sheet
balance_sheet_data = get_balance_sheet_data(symbol)
balance_sheet_data

,2023-03-31,2022-03-31,2021-03-31,2020-03-31
Ordinary Shares Number,49181562.0,49635447.0,48838261.0,48316559.0
Share Issued,49181562.0,49635447.0,48838261.0,48316559.0
Net Debt,160913000.0,148198000.0,148297000.0,265732000.0
Total Debt,539172000.0,532335000.0,501853000.0,713247000.0
Tangible Book Value,17460000.0,-18001000.0,-76815000.0,-153876000.0
...,...,...,...,...
Loans Receivable,NaN,9308000.0,8445000.0,3326000.0
Accounts Receivable,25870000.0,30225000.0,28949000.0,20217000.0
Cash Cash Equivalents And Short Term Investments,6958000.0,14252000.0,17687000.0,67755000.0
Cash And Cash Equivalents,6958000.0,14252000.0,17687000.0,67755000.0
Cash Financial,6958000.0,14252000.0,17687000.0,67755000.0

# Cash Flow Statement

In [34]:
# Create the function for cash Flow statement
def get_cash_flow_data(symbol):
    company = yf.Ticker(symbol)
    cash = company.cash_flow
    return cash

symbol = "TCS" # Change the comapny symbol as per your requirement
get_cash_flow_data = get_cash_flow_data(symbol)
get_cash_flow_data

,2023-03-31,2022-03-31,2021-03-31,2020-03-31
Free Cash Flow,-4918000.0,23601000.0,121111000.0,-2871000.0
Repurchase Of Capital Stock,-5000000.0,NaN,NaN,NaN
Repayment Of Debt,-116589000.0,-118436000.0,-422181000.0,-113836000.0
Issuance Of Debt,120292000.0,113167000.0,256132000.0,178603000.0
Capital Expenditure,-64223000.0,-33389000.0,-17176000.0,-33619000.0
Interest Paid Supplemental Data,13688000.0,10745000.0,16661000.0,18316000.0
Income Tax Paid Supplemental Data,21275000.0,30163000.0,16939000.0,13944000.0
End Cash Position,6958000.0,14252000.0,17687000.0,67755000.0
Beginning Cash Position,14252000.0,17687000.0,67755000.0,7364000.0
Effect Of Exchange Rate Changes,-519000.0,-622000.0,819000.0,-1149000.0
Changes In Cash,-6775000.0,-2813000.0,-50887000.0,61540000.0
Financing Cash Flow,-1669000.0,-9381000.0,-172063000.0,64394000.0
Cash Flow From Continuing Financing Activities,-1669000.0,-9381000.0,-172063000.0,64394000.0
Net Other Financing Charges,-712000.0,-4677000.0,-6510000.0,-373000.0
Proceeds From Stock Option Exercised,340000.0,565000.0,496000.0,NaN
Net Common Stock Issuance,-5000000.0,NaN,NaN,NaN
Common Stock Payments,-5000000.0,NaN,NaN,NaN
Net Issuance Payments Of Debt,3703000.0,-5269000.0,-166049000.0,64767000.0
Net Short Term Debt Issuance,795000.0,1898000.0,-10095000.0,4018000.0
Short Term Debt Payments,-79497000.0,-73269000.0,-66227000.0,-59585000.0
Short Term Debt Issuance,80292000.0,75167000.0,56132000.0,63603000.0
Net Long Term Debt Issuance,2908000.0,-7167000.0,-155954000.0,60749000.0
Long Term Debt Payments,-37092000.0,-45167000.0,-355954000.0,-54251000.0
Long Term Debt Issuance,40000000.0,38000000.0,200000000.0,115000000.0
Investing Cash Flow,-64411000.0,-50422000.0,-17111000.0,-33602000.0
Cash Flow From Continuing Investing Activities,-64411000.0,-50422000.0,-17111000.0,-33602000.0
Net Other Investing Changes,NaN,2346000.0,NaN,NaN
Net Investment Purchase And Sale,-231000.0,NaN,NaN,NaN
Sale Of Investment,916000.0,NaN,NaN,NaN
Purchase Of Investment,-1147000.0,NaN,NaN,NaN
Net Business Purchase And Sale,0.0,-19445000.0,NaN,NaN
Purchase Of Business,0.0,-19445000.0,NaN,NaN
Net PPE Purchase And Sale,-64180000.0,-33323000.0,-17111000.0,-33602000.0
Sale Of PPE,43000.0,66000.0,65000.0,17000.0
Purchase Of PPE,-64223000.0,-33389000.0,-17176000.0,-33619000.0
Operating Cash Flow,59305000.0,56990000.0,138287000.0,30748000.0
Cash Flow From Continuing Operating Activities,59305000.0,56990000.0,138287000.0,30748000.0
Change In Working Capital,-24552000.0,-67414000.0,39250000.0,-27811000.0
Change In Other Working Capital,-4200000.0,-8043000.0,7228000.0,-6827000.0
Change In Other Current Liabilities,-370000.0,-2547000.0,2912000.0,-247000.0
Change In Payables And Accrued Expense,-37684000.0,9814000.0,35203000.0,-3531000.0
Change In Payable,-37684000.0,NaN,NaN,NaN
Change In Account Payable,-37684000.0,NaN,NaN,NaN
Change In Prepaid Assets,-4584000.0,-1474000.0,-2193000.0,1089000.0
Change In Inventory,20450000.0,-63533000.0,-2403000.0,-17293000.0
Change In Receivables,1836000.0,-1631000.0,-1497000.0,-1002000.0
Changes In Account Receivables,1836000.0,-1631000.0,-1497000.0,-1002000.0
Other Non Cash Items,2943000.0,562000.0,2031000.0,2178000.0
Stock Based Compensation,3382000.0,4263000.0,7823000.0,3110000.0
Asset Impairment Charge,197712000.0,NaN,NaN,NaN
Deferred Tax,-351000.0,3621000.0,-4740000.0,148000.0
Deferred Income Tax,-351000.0,3621000.0,-4740000.0,148000.0
Depreciation Amortization Depletion,38905000.0,34289000.0,34731000.0,38638000.0
Depreciation And Amortization,38905000.0,34289000.0,34731000.0,38638000.0
Operating Gains Losses,122000.0,-49000.0,909000.0,-2000.0
Net Income From Continuing Operations,-158856000.0,81718000.0,58283000.0,14487000.0

# Income Statement

In [35]:

# Create the function for Income Statement
def get_income_statement_data(symbol):
    company = yf.Ticker(symbol)
    inc = company.financials
    return inc

symbol = "TCS" # Change the comapny symbol as per your requirement
get_income_statement_data = get_income_statement_data(symbol)
get_income_statement_data

,2023-03-31,2022-03-31,2021-03-31,2020-03-31
Tax Effect Of Unusual Items,-79133600.0,13475.0,-253665.00501,634.0
Tax Rate For Calcs,0.4,0.275,0.279059,0.317
Normalized EBITDA,109144000.0,159694000.0,133751000.0,81379000.0
Total Unusual Items,-197834000.0,49000.0,-909000.0,2000.0
Total Unusual Items Excluding Goodwill,-197834000.0,49000.0,-909000.0,2000.0
Net Income From Continuing Operation Net Minority Interest,-158856000.0,81718000.0,58283000.0,14487000.0
Reconciled Depreciation,38905000.0,34289000.0,34731000.0,38638000.0
Reconciled Cost Of Revenue,446295000.0,457882000.0,419611000.0,382488000.0
EBIT,-127595000.0,125454000.0,98111000.0,42743000.0
Net Interest Income,-16171000.0,-12760000.0,-17268000.0,-21541000.0
Interest Expense,16171000.0,12760000.0,17268000.0,21541000.0
Normalized Income,-40155600.0,81682475.0,58938334.99499,14485634.0
Net Income From Continuing And Discontinued Operation,-158856000.0,81718000.0,58283000.0,14487000.0
Total Expenses,977019000.0,968714000.0,891068000.0,873212000.0
Total Operating Income As Reported,-127595000.0,125454000.0,99004000.0,42743000.0
Diluted Average Shares,49539875.0,50294118.0,49712637.0,48964564.0
Basic Average Shares,49539875.0,49447612.0,48537883.0,48819783.0
Diluted EPS,-3.21,1.62,1.17,0.3
Basic EPS,-3.21,1.65,1.2,0.3
Diluted NI Availto Com Stockholders,-158856000.0,81718000.0,58283000.0,14487000.0
Net Income Common Stockholders,-158856000.0,81718000.0,58283000.0,14487000.0
Net Income,-158856000.0,81718000.0,58283000.0,14487000.0
Net Income Including Noncontrolling Interests,-158856000.0,81718000.0,58283000.0,14487000.0
Net Income Continuous Operations,-158856000.0,81718000.0,58283000.0,14487000.0
Tax Provision,15090000.0,30976000.0,22560000.0,6715000.0
Pretax Income,-143766000.0,112694000.0,80843000.0,21202000.0
Other Income Expense,-197834000.0,49000.0,-909000.0,2000.0
Other Non Operating Income Expenses,NaN,NaN,NaN,-377000.0
Special Income Charges,-197834000.0,49000.0,-909000.0,2000.0
Gain On Sale Of Ppe,-122000.0,49000.0,-16000.0,2000.0
Other Special Charges,2006000.0,694000.0,893000.0,8237000.0
Write Off,197712000.0,NaN,NaN,NaN
Net Non Operating Interest Income Expense,-16171000.0,-12760000.0,-17268000.0,-21541000.0
Interest Expense Non Operating,16171000.0,12760000.0,17268000.0,21541000.0
Operating Income,70239000.0,125405000.0,99020000.0,42741000.0
Operating Expense,530724000.0,510832000.0,471457000.0,490724000.0
Other Operating Expenses,2006000.0,694000.0,2138000.0,8614000.0
Depreciation Amortization Depletion Income Statement,38905000.0,34289000.0,34731000.0,38638000.0
Depreciation And Amortization In Income Statement,38905000.0,34289000.0,34731000.0,38638000.0
Selling General And Administration,489813000.0,475849000.0,434588000.0,443472000.0
General And Administrative Expense,489813000.0,475849000.0,434588000.0,443472000.0
Other Gand A,486431000.0,471586000.0,426765000.0,440362000.0
Salaries And Wages,3382000.0,4263000.0,7823000.0,3110000.0
Gross Profit,600963000.0,636237000.0,570477000.0,533465000.0
Cost Of Revenue,446295000.0,457882000.0,419611000.0,382488000.0
Total Revenue,1047258000.0,1094119000.0,990088000.0,915953000.0
Operating Revenue,1047258000.0,1094119000.0,990088000.0,915953000.0